[[section-introduction-and-goals]]
== Introducción y Metas

[role="arc42help"]
****
Describe los requerimientos relevantes y las directrices que los arquitectos de software y el equipo de desarrollo
deben considerar. Entre estas se incluyen:

* Objetivos empresariales subyacentes, características esenciales y requerimientos funcionales para el sistema
* Metas de calidad para la arquitectura
* Las partes interesadas pertinentes y sus expectativas
****

=== Vista de Requerimientos

[role="arc42help"]
****
.Contenido
Descripción corta de los requerimientos funcionales, motivaciones, extracto (o resumen) de los 
requerimientos. Ligar a los documentos de requerimientos determinados (Con número de versión e
información de donde encontrarla). 

.Motivación
Desde el punto de vista de los usuarios finales un sistema es creado o modificado para
mejorar el soporte a una actividad de negocio o incrementar su calidad

.Forma
Descripción corta textual, probablemente en un formato de caso de uso tabular.
Si existen documentos de requerimientos esta vista debe referir a dichos requerimientos

Mantenga estos extractos tan cortos como sea posible. Encuentre el balance entre la legibilidad y 
la redundancia de este documento respecto a los documentos de requerimientos que se encuentren 
relacionados.
****

=== Metas de Calidad

[role="arc42help"]
****
.Contenido
Las tres metas de calidad principales (o hasta cinco) cuyo cumplimiento sea de la mayor importancia para las
principales partes interesadas. Nos referimos a las metas de calidad para la arquitectura. No confundir
con las metas del proyecto. No necesariamente son idénticas.

.Motivación
Debe conocer las metas de calidad de las partes interesadas más importantes, ya que ellos influenciarán
las decisiones arquitectónicas principales. Asegúrese de ser muy concreto con las descripciones, evitando buzzwords.
Si como arquitecto no conoce la calidad de su trabajo, será juzgado...

.Forma
Una tabla con metas de calidad y escenarios concretos, ordenados por prioridades
****

=== Partes interesadas (Stakeholders)

[role="arc42help"]
****

[options="header",cols="1,2,2"]
|===
|Rol/Nombre|Contacto|Expectativas
| Equipo de desarrollo | Mediante reuniones en las que organizamos el trabajo personal y un control de versiones, en este caso GitHub | Conseguir desarrollar un producto funcional y que siga las necesidades y demandas del cliente
| Profesor | Hará un seguimiento del desarrollo del proyecto durante los laboratorios, donde también podemos preguntarle dudas. Para la revisión de las versiones definitivas del proyecto, observará como ha ido el desarrollo mediante GitHub, es decir, revisará lo que ha hecho cada uno | Ser un punto de apoyo al equipo de desarrollo, para que este consiga implementar un producto funcional
| Cliente(Solid) | Hay foros y charlas en las que ellos participan y en las que nosotros podemos consultar dudas, aprender de dudas que hayan tenido otros equipos de desarrollo y entender mejor cual es el producto final que quiere el cliente. | Obtener un producto funcional y que se adecue a los objetivos de calidad que ha establecido con el equipo de desarrollo al principio del proyecto
| Usuarios | Cuando el producto este acabado, estos podrán valorarlo mediante diferentes canales de comunicación que llegarán a nosotros. Gracias a esto, ellos pueden detectar errores al usarlo que nos podrán notificar y que nosotros podremos corregir | Poder usar un producto final que funcione, que sea fácil de utilizar y que sea útil
|===
****
