[[section-system-scope-and-context]]
== Alcance y Contexto del Sistema



****
.Contenido
|==================================================
|Socios de comunicacion | Entendimiento
|Clientes | Interactuan de forma normal con la aplicacion de DeChat, conversando con otras personas, mandando imagenes etc.
|DeChat | Una vez que el cliente envia un mensaje, imagen o similar, se iniciara una "comunicación" con el POD personal de ese cliente, mediante la libreria "solid-auth-client", para guardar en ese POD el mensaje y posteriormente enviar un enlace al otro cliente con el que se esta manteniendo una conversacion de ese mensaje que acaba de enviar concediendole permiso para ver SOLO ese mensaje. Pero siempre manteniendo ese mensaje en el POD personal del primer cliente, esto es lo que se consigue con descentralizacion.
Seria tambien factible que alguno de los clientes tuviese varios POD y distribuyera los datos entre ellos en cualquier caso el funcionamiento seguiria siendo el mismo, solamente aumenta la descentralizacion.
|POD | Son almacenes de datos personas en linea y va a estar alojado donde el usuario lo estime oportuno.
Aqui es donde van a estar almacenados toda la informacion, mensajes, etc. Que haya comunicado el cliente con la aplicacion de DeChat.
|==================================================

.Motivación
Las interfases de dominio y las interfases técnicas a los socios de comunicación son de los aspectos más críticos del sistema.
Se debe asegurar el entendimiento de ellos.

.Forma
Forma utilizada:

* Listas de socios de comunicación y sus interfases.
****


=== Contexto de Negocio

[role="arc42help"]
****
.Contenido
La especificación de *todos* los socios de comunicación (usuarios, sistemas, ...) con explicaciones de las entradas y salidas
específicas del dominio o interfases.
Opcionalmente puede agregar formatos específicos de dominio o protocolos de comunicación

.Motivación
Todas las partes interesadas deben entender que datos son intercambiados con el ambiente del sistema.

.Forma
Cualquier forma de diagramas que muestren al sistema como una caja negra y especifiquen las interfases de dominio a los
socios de comunicación.

De manera alternativa (o adicional) se puede utilizar una tabla.
El título de la tabla es el nombre del sistema, las tres columnas contienen el nombre del socio de comunicación, las
entradas y las salidas
****

**<Diagrama o Tabla>**

**<optionally: Explanation of external domain interfaces>**

=== Contexto Técnico

[role="arc42help"]
****
.Contenido
Las interfases técnicas (medios de transmisión y canales) enlanzando al sistema con su ambiente. De manera adicional
el mapeo de las entradas/salidas específicas del dominio a los canales, es decir, una explicación acerca de que entrada/salida
utiliza cual canal.

.Motivación
Muchas partes relacionadas realizan decisiones arquitectónicas basadas en las interfases técnicas entre el sistema y 
su contexto. Especialmente los diseñadores de infraestructura o hardware deciden estas interfases técnicas.

.Forma
Por ejemplo, diagramas UML de despligue describiendo los canales a sistemas vecinos, junto con una tabla de 
mapeo mostrando las relaciones entre los canales y las entradas/salidas.
****

**<Diagrama o Tabla>**

**<Opcional: Explicación de las interfases técnicas>**

**<Mapeo de Entrada/Salida a canales>**
